figure('Name','Circuit oscilator cu retea Wien',... 
'Units','normalized',...
'NumberTitle','off',...
'NumberTitle','off',...
'Position',[0.1,0.1,0.8,0.8]);
ah=axes('unit','normalized', 'position', [0 0 1 1]);
bg=imread('circuit.jpg');
imagesc(bg);
set(ah, 'handlevisibility','off','visible','off')
