figure('Name','Despre oscilatorul cu retea Wien',... 
'Units','normalized',...
'NumberTitle','off',...
'NumberTitle','off',...
'Position',[0.1,0.1,0.8,0.8]);
ah=axes('unit','normalized', 'position', [0 0 1 1]);
bg=imread('ptproiect.jpg');
imagesc(bg);
set(ah, 'handlevisibility','off','visible','off')


BACK = uicontrol('style','pushbutton',...
     'Units','normalized',...
    'String',' Inchide',...
    'backgroundcolor','k',...             
    'BackgroundColor',[0.28,0.23,0.46] ,...
    'ForegroundColor',[0.8 0.7 0.7],...
    'Fontname','Comic Sans MS',...
    'FontWeight','bold',...
    'fontsize',17,...
    'Position',[0.2 0.10 0.27 0.1],...
    'Callback','close;');
BACK = uicontrol('style','pushbutton',...
              'Units','normalized',...
              'String',' MENIU',...
              'backgroundcolor','k',...             
              'BackgroundColor',[0.28,0.23,0.46] ,...
              'ForegroundColor',[0.8 0.7 0.7],...
              'Fontname','Comic Sans MS',...
              'FontWeight','bold',...
              'fontsize',17,...
              'Position',[0.5 0.10 0.27 0.1],...
              'Callback','close;start_proiect;');
          
          
          

Bp=uicontrol('Style','pushbutton',...
                'Units','normalized',...
                'backgroundcolor','k',...             
                'BackgroundColor',[0.28,0.23,0.46] ,...
                'ForegroundColor',[0.8 0.7 0.7],...
                'Fontname','Comic Sans MS',...
                'FontWeight','bold',...
                'fontsize',17,...
                'Position',[0.16 0.50 0.16 0.2],...
                'String','Documentatie',...
                'Callback','open(''Oscilatoare_sinusoidale.ppt'')');
            
            
  Bp=uicontrol('Style','pushbutton',...
                'Units','normalized',...
                'backgroundcolor','k',...             
                'BackgroundColor',[0.28,0.23,0.46] ,...
                'ForegroundColor',[0.8 0.7 0.7],...
                'Fontname','Comic Sans MS',...
                'FontWeight','bold',...
                'fontsize',17,...
                'Position',[0.46 0.50 0.16 0.2],...
                'String','Circuit',...
                'Callback','circuit;');
            
   Bp=uicontrol('Style','pushbutton',...
                'Units','normalized',...
                'backgroundcolor','k',...             
                'BackgroundColor',[0.28,0.23,0.46] ,...
                'ForegroundColor',[0.8 0.7 0.7],...
                'Fontname','Comic Sans MS',...
                'FontWeight','bold',...
                'fontsize',17,...
                'Position',[0.74 0.50 0.16 0.2],...
                'String','Functionare interfata',...
                'Callback','open(''Utilizare.ppt'')');
       