clear all;
close all;


figure('Name','Oscilator cu retea Wien',... 
'Units','normalized',...
'NumberTitle','off',...
'NumberTitle','off',...
'Position',[0.1,0.1,0.8,0.8]);

ah=axes('unit','normalized', 'position', [0 0 1 1]);
bg=imread('ptproiect.jpg');
imagesc(bg);
set(ah, 'handlevisibility','off','visible','off')


    Bp=uicontrol('Style','pushbutton',...
                'Units','normalized',...
                'backgroundcolor','k',...             
                'BackgroundColor',[0.28,0.23,0.46] ,...
                'ForegroundColor',[0.8 0.7 0.7],...
                'Fontname','Comic Sans MS',...
                'FontWeight','bold',...
                'fontsize',17,...
                'Position',[0.18 0.40 0.16 0.2],...
                'String','Continut',...
                'Callback','close,despre');
            
            
                
    Bp=uicontrol('Style','pushbutton',...
             'Units','normalized',...
             'backgroundcolor','k',...             
             'BackgroundColor',[0.28,0.23,0.46] ,...
             'ForegroundColor',[0.8 0.7 0.7],...
             'Fontname','Comic Sans MS',...
             'FontWeight','bold',...
             'fontsize',17,...
             'Position',[0.65 0.40 0.16 0.2],...
             'String','Circuit. Functionare circuit',...
             'Callback','close,start_proiect2');


Bt=uicontrol('Style','text',...
             'Units','normalized',...
             'Position',[0.27 0.82 0.40 0.1],...
             'backgroundcolor',[0.2 0.4 0.7],...    
             'foregroundcolor','w',...
             'FontSize',20,...
             'String','Oscilator cu retea Wien');
         
         
         
          Bt=uicontrol('Style','text',...
                      'Units','normalized',...
                      'Position',[0.8 0.1 0.2 0.1],...
                      'backgroundcolor',[0.2 0.4 0.7],...    
                      'foregroundcolor','w',...
                      'FontSize',12,...
                      'String',' ONOFREI IOAN-CRISTIAN | GRUPA 2121');
         
         
         
         BACK = uicontrol('style','pushbutton',...
                          'Units','normalized',...
                          'String',' Inchide',...
                          'backgroundcolor','k',...             
                          'BackgroundColor',[0.28,0.23,0.46] ,...
                          'ForegroundColor',[0.8 0.7 0.7],...
                          'Fontname','Comic Sans MS',...
                          'FontWeight','bold',...
                          'fontsize',17,...
                          'Position',[0.35 0.10 0.27 0.1],...
                          'Callback','close;');

         
         
         
         